[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/shop/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/orders"
  to = "/orders.html"
  status = 200
